# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Marc Dobler
email: me@marcdobler.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marcdobler
github_username:  marcdobler

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-pwa-workbox

# Google Analytics
google_analytics: UA-108639938-3
show_excerpts: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

minima:
  social_links:
    twitter: marcdobler
    github: marcdobler
    #stackoverflow: "11111"
    #dribbble: jekyll
    facebook: marcdoblermaker
    #flickr: jekyll
    instagram: marcdobler_maker
    linkedin: marcdobler
    #pinterest: jekyll
    #telegram: jekyll
    #microdotblog: jekyll
    #keybase: jekyll
    youtube: UCm4nKwBw6IfdwJQvIVE0uLg
    #youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    #youtube_channel_name: CloudCannon

# Build PWA settings

pwa:
  sw_src_filepath: sw-register.js # Optional
  sw_dest_filename: sw-register.js # Optional
  dest_js_directory: assets/script # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{js,json,css}"
    - "/**/*.{ico,jpg,jpeg,png,svg}"
    - "/**/*.html"
  precache_glob_ignores: # Optional
    - "sw-register.js"
    - "fonts/**/*"

collections:
  projects:
    output: true
    sort_by: date
  tags:
    output: true
    permalink: tags/:path/